<section id="about" class="content-section text-center">
      <div class="container">
        <div class="row">
          <div class="col-lg-8 mx-auto">     
    <div class="img-box" >
            <center><img border="1" src="img/na2.png" alt="this is my picture" id="pic" width="50%" height="50%" ></center>
            <br>
            <b><center> 590610663 Satatan Chamboonchu</center> </b>
            </div>
          </div>
        </div>
      </div>
    </section>